package render

import (
	"fmt"
	"html/template"
	"io"

	"github.com/kleio-build/kleio-cli/internal/engine"
)

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Command}} Report: {{.Anchor}}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #1a1a1a; line-height: 1.6; }
  h1 { border-bottom: 2px solid #333; padding-bottom: 0.3rem; }
  h2 { margin-top: 2rem; color: #444; }
  .enriched { color: #0969da; font-size: 0.85rem; }
  .subject { font-size: 1.1rem; margin: 1rem 0; }
  table { border-collapse: collapse; width: 100%%; margin: 0.5rem 0; }
  th, td { border: 1px solid #ddd; padding: 0.4rem 0.6rem; text-align: left; }
  th { background: #f6f8fa; }
  code { background: #f0f0f0; padding: 0.15rem 0.35rem; border-radius: 3px; font-size: 0.9em; }
  .deferred { opacity: 0.6; }
  .next-steps li { margin: 0.3rem 0; }
  .note { color: #666; font-style: italic; }
  .timeline { font-family: monospace; font-size: 0.85rem; white-space: pre-wrap; background: #f6f8fa; padding: 1rem; border-radius: 4px; }
</style>
</head>
<body>
<h1>{{.CommandTitle}} Report: {{.Anchor}}</h1>
{{if .Enriched}}<p class="enriched">Enriched by LLM</p>{{end}}
<div class="subject"><strong>About:</strong> {{.Subject}}</div>

{{range .Sections}}{{.}}{{end}}

{{if .NextSteps}}
<h2>Next Steps</h2>
<ol class="next-steps">
{{range .NextSteps}}<li><code>{{.}}</code></li>
{{end}}</ol>
{{end}}

{{if .ShowTimeline}}
<h2>Raw Timeline</h2>
<div class="timeline">{{range .Timeline}}[{{.Kind}}] {{.TS}} {{.Summary}}
{{end}}</div>
{{end}}

<footer style="margin-top:2rem;border-top:1px solid #eee;padding-top:0.5rem;color:#999;font-size:0.8rem;">
  Generated by kleio-cli at {{.GeneratedAt}}
</footer>
</body>
</html>
`

type htmlData struct {
	Command      string
	CommandTitle string
	Anchor       string
	Enriched     bool
	Subject      string
	Sections     []template.HTML
	NextSteps    []string
	ShowTimeline bool
	Timeline     []htmlTimelineEntry
	GeneratedAt  string
}

type htmlTimelineEntry struct {
	Kind    string
	TS      string
	Summary string
}

// RenderHTML writes a standalone HTML report to w.
func RenderHTML(w io.Writer, r engine.Report, verbose bool) error {
	tmpl, err := template.New("report").Parse(htmlTemplate)
	if err != nil {
		return err
	}

	data := htmlData{
		Command:      r.Command,
		CommandTitle: capitalize(r.Command),
		Anchor:       r.Anchor,
		Enriched:     r.Enriched,
		Subject:      r.Subject,
		NextSteps:    r.NextSteps,
		ShowTimeline: verbose && len(r.RawTimeline) > 0,
		GeneratedAt:  r.GeneratedAt.Format("2006-01-02 15:04:05 UTC"),
	}

	for _, e := range r.RawTimeline {
		data.Timeline = append(data.Timeline, htmlTimelineEntry{
			Kind:    e.Kind,
			TS:      e.Timestamp.Format("2006-01-02 15:04"),
			Summary: e.Summary,
		})
	}

	for _, sec := range sectionOrder(r.Command) {
		html := renderHTMLSection(sec, r)
		if html != "" {
			data.Sections = append(data.Sections, template.HTML(html))
		}
	}

	return tmpl.Execute(w, data)
}

func renderHTMLSection(sec string, r engine.Report) string {
	switch sec {
	case "decisions":
		if len(r.Decisions) == 0 {
			return ""
		}
		s := "<h2>Decisions</h2>\n<ul>\n"
		for _, d := range r.Decisions {
			s += fmt.Sprintf("<li><strong>%s</strong>", template.HTMLEscapeString(d.Content))
			if d.Rationale != "" {
				s += fmt.Sprintf("<br><em>Rationale: %s</em>", template.HTMLEscapeString(d.Rationale))
			}
			s += "</li>\n"
		}
		return s + "</ul>\n"

	case "open_threads":
		if len(r.OpenThreads) == 0 {
			return ""
		}
		heading := "Open Threads"
		if r.Command == "explain" {
			heading = "Review Risks"
		}
		s := fmt.Sprintf("<h2>%s</h2>\n<ul>\n", heading)
		for _, t := range r.OpenThreads {
			cls := ""
			suffix := ""
			if t.Deferred {
				cls = ` class="deferred"`
				suffix = " <em>[deferred]</em>"
			}
			s += fmt.Sprintf("<li%s>%s (×%d)%s</li>\n",
				cls, template.HTMLEscapeString(t.Content), t.Occurrences, suffix)
		}
		return s + "</ul>\n"

	case "code_changes":
		if len(r.CodeChanges) == 0 {
			return ""
		}
		s := "<h2>Code Changes</h2>\n<table>\n<tr><th>SHA</th><th>Date</th><th>Subject</th></tr>\n"
		for _, c := range r.CodeChanges {
			sha := c.SHA
			if len(sha) > 7 {
				sha = sha[:7]
			}
			s += fmt.Sprintf("<tr><td><code>%s</code></td><td>%s</td><td>%s</td></tr>\n",
				sha, c.Date, template.HTMLEscapeString(c.Subject))
		}
		return s + "</table>\n"

	case "evidence_quality":
		s := "<h2>Evidence Quality</h2>\n<ul>\n"
		s += fmt.Sprintf("<li><strong>Fidelity</strong>: %s</li>\n", r.EvidenceQuality.HistoryFidelity)
		for src, n := range r.EvidenceQuality.SourceCounts {
			s += fmt.Sprintf("<li>%s: %d</li>\n", template.HTMLEscapeString(src), n)
		}
		for _, note := range r.EvidenceQuality.Notes {
			s += fmt.Sprintf("<li class=\"note\">%s</li>\n", template.HTMLEscapeString(note))
		}
		return s + "</ul>\n"
	}
	return ""
}
