package render

import (
	"fmt"
	"io"
	"strings"

	"github.com/go-pdf/fpdf"
	"github.com/kleio-build/kleio-cli/internal/engine"
)

// asciiSafeReplacer replaces common UTF-8 punctuation/symbol code points with
// ASCII fallbacks. fpdf's default encoding is WinAnsi (cp1252), so any
// non-WinAnsi rune is dropped or mojibake'd. Using ASCII keeps the binary
// small (no embedded UTF-8 font) and renders predictably across viewers.
var asciiSafeReplacer = strings.NewReplacer(
	"\u2022", "*",
	"\u2023", "*",
	"\u25E6", "*",
	"\u2043", "*",
	"\u2192", "->",
	"\u2190", "<-",
	"\u00D7", "x",
	"\u2014", "--",
	"\u2013", "-",
	"\u2018", "'",
	"\u2019", "'",
	"\u201C", "\"",
	"\u201D", "\"",
	"\u2026", "...",
	"\u00A0", " ",
)

// asciiSafe rewrites s so every rune is representable in fpdf's default
// WinAnsi encoding. Non-replaced multi-byte runes are stripped.
func asciiSafe(s string) string {
	s = asciiSafeReplacer.Replace(s)
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if r < 0x80 {
			b.WriteRune(r)
			continue
		}
		// Keep WinAnsi-representable Latin-1 punctuation (0x80-0xFF) but drop
		// anything else, since fpdf's default font cannot render it.
		if r >= 0xA0 && r <= 0xFF {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// RenderPDF writes a PDF report directly (not via HTML).
func RenderPDF(w io.Writer, r engine.Report, verbose bool) error {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 15)
	pdf.AddPage()

	pdf.SetFont("Helvetica", "B", 18)
	pdf.MultiCell(0, 10, asciiSafe(fmt.Sprintf("%s Report: %s", capitalize(r.Command), r.Anchor)), "", "L", false)
	pdf.Ln(4)

	if r.Enriched {
		pdf.SetFont("Helvetica", "I", 9)
		pdf.SetTextColor(9, 105, 218)
		pdf.MultiCell(0, 5, asciiSafe("Enriched by LLM"), "", "L", false)
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(2)
	}

	pdfSection(pdf, "About")
	pdf.SetFont("Times", "", 11)
	pdf.MultiCell(0, 5, asciiSafe(r.Subject), "", "L", false)
	pdf.Ln(4)

	for _, sec := range sectionOrder(r.Command) {
		renderPDFSection(pdf, sec, r)
	}

	if len(r.NextSteps) > 0 {
		pdfSection(pdf, "Next Steps")
		pdf.SetFont("Courier", "", 10)
		for i, s := range r.NextSteps {
			pdf.MultiCell(0, 5, asciiSafe(fmt.Sprintf("%d. %s", i+1, s)), "", "L", false)
		}
		pdf.Ln(3)
	}

	if verbose && len(r.RawTimeline) > 0 {
		pdf.AddPage()
		pdfSection(pdf, "Raw Timeline")
		pdf.SetFont("Courier", "", 8)
		for _, e := range r.RawTimeline {
			line := fmt.Sprintf("[%s] %s %s", e.Kind, e.Timestamp.Format("2006-01-02 15:04"), e.Summary)
			pdf.MultiCell(0, 4, asciiSafe(line), "", "L", false)
		}
	}

	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(150, 150, 150)
	pdf.Ln(6)
	// Footer is fixed-width and centered; CellFormat is appropriate here.
	pdf.CellFormat(0, 4, asciiSafe(fmt.Sprintf("Generated by kleio-cli at %s", r.GeneratedAt.Format("2006-01-02 15:04:05 UTC"))), "", 1, "C", false, 0, "")

	return pdf.Output(w)
}

func pdfSection(pdf *fpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", 13)
	pdf.MultiCell(0, 8, asciiSafe(title), "", "L", false)
	pdf.SetDrawColor(200, 200, 200)
	pdf.Line(pdf.GetX(), pdf.GetY(), pdf.GetX()+190, pdf.GetY())
	pdf.Ln(2)
}

func renderPDFSection(pdf *fpdf.Fpdf, sec string, r engine.Report) {
	switch sec {
	case "decisions":
		if len(r.Decisions) == 0 {
			return
		}
		pdfSection(pdf, "Decisions")
		pdf.SetFont("Times", "", 10)
		for _, d := range r.Decisions {
			pdf.MultiCell(0, 5, asciiSafe("* "+d.Content), "", "L", false)
			if d.Rationale != "" {
				pdf.SetFont("Times", "I", 9)
				pdf.MultiCell(0, 4, asciiSafe("    Rationale: "+d.Rationale), "", "L", false)
				pdf.SetFont("Times", "", 10)
			}
		}
		pdf.Ln(3)

	case "open_threads":
		if len(r.OpenThreads) == 0 {
			return
		}
		heading := "Open Threads"
		if r.Command == "explain" {
			heading = "Review Risks"
		}
		pdfSection(pdf, heading)
		pdf.SetFont("Times", "", 10)
		for _, t := range r.OpenThreads {
			suffix := ""
			if t.Deferred {
				suffix = " [deferred]"
			}
			pdf.MultiCell(0, 5, asciiSafe(fmt.Sprintf("* %s (x%d)%s", t.Content, t.Occurrences, suffix)), "", "L", false)
		}
		pdf.Ln(3)

	case "code_changes":
		if len(r.CodeChanges) == 0 {
			return
		}
		pdfSection(pdf, "Code Changes")
		pdf.SetFont("Courier", "", 9)
		for _, c := range r.CodeChanges {
			sha := c.SHA
			if len(sha) > 7 {
				sha = sha[:7]
			}
			pdf.MultiCell(0, 4, asciiSafe(fmt.Sprintf("%s  %s  %s", sha, c.Date, c.Subject)), "", "L", false)
		}
		pdf.Ln(3)

	case "evidence_quality":
		pdfSection(pdf, "Evidence Quality")
		pdf.SetFont("Times", "", 10)
		pdf.MultiCell(0, 5, asciiSafe(fmt.Sprintf("Fidelity: %s", r.EvidenceQuality.HistoryFidelity)), "", "L", false)
		for src, n := range r.EvidenceQuality.SourceCounts {
			pdf.MultiCell(0, 5, asciiSafe(fmt.Sprintf("%s: %d", src, n)), "", "L", false)
		}
		for _, note := range r.EvidenceQuality.Notes {
			pdf.SetFont("Times", "I", 9)
			pdf.MultiCell(0, 4, asciiSafe(note), "", "L", false)
			pdf.SetFont("Times", "", 10)
		}
		pdf.Ln(3)
	}
}
